<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Free CRM App Test Cases"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="3.642">
  <properties />
            <testcase name="verifyLoginTest" time="3.409" classname="com.crm.testcases.LoginPageTest">
                <failure type="java.lang.AssertionError"
                  message="expected [CRMPRO] but found [Free CRM software in the cloud powers sales and customer service]"
              >
<![CDATA[java.lang.AssertionError: expected [CRMPRO] but found [Free CRM software in the cloud powers sales and customer service]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:453)
  org.testng.Assert.assertEquals(Assert.java:463)
  com.crm.testcases.LoginPageTest.verifyLoginTest(LoginPageTest.java:43)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.runSuites(TestNG.java:1028)
  org.testng.TestNG.run(TestNG.java:996)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="titleTest" time="0.038" classname="com.crm.testcases.LoginPageTest" />
                <testcase name="verifyFreeCRMLogoTest" time="0.195" classname="com.crm.testcases.LoginPageTest" />
      
</testsuite>
